inp = input("input float number here : ")
print(f"1 inp data is : {inp}")
print(f" inp+inp is : {inp+inp}")
print(f" inp datatype is : {type(inp)}")
inp = float(inp)
print(f"2 inp data is : {inp}")
print(f" inp+inp is : {inp+inp}")
print(f" inp datatype is : {type(inp)}")
inp = int(inp)
print(f"3 inp data is : {inp}")
print(f" inp+inp is : {inp+inp}")
print(f" inp datatype is : {type(inp)}")
